apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microapp
type: Opaque
stringData:
  secret-key: "mp2_secret_key_cambiar"
  users-db-password: "users123"
  products-db-password: "products123"
  orders-db-password: "orders123"
