apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-orders
  namespace: microapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-orders
  template:
    metadata:
      labels:
        app: mysql-orders
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: orders-db-password
            - name: MYSQL_DATABASE
              value: orders_db
          volumeMounts:
            - name: init
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              memory: "768Mi"
      volumes:
        - name: init
          configMap:
            name: orders-db-init
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-orders
  namespace: microapp
spec:
  selector:
    app: mysql-orders
  ports:
    - port: 3306
      targetPort: 3306
